### ISSUE TITLE
What is the dataset used to train DBoW in ORB_SLAM2?

### ISSUE THREAD

**Issue by RupertPaoZ** [raulmur/ORB_SLAM2#1013]

**Comment by XinnWang** [comment]
@RupertPaoZ Same problem here. Have you found the dataset ?

**Comment by RupertPaoZ** [comment]
> @RupertPaoZ Same problem here. Have you found the dataset ?

`Bovisa_2008-09-01-FRONTAL`

**Comment by XinnWang** [comment]
@RupertPaoZ Thanks. Its download torrent is out-of-date, how did you download it ? Any possible links for it?

**Comment by RupertPaoZ** [comment]
> @RupertPaoZ Thanks. Its download torrent is out-of-date, how did you download it ? Any possible links for it?

I remember that its ftp is available.

**Comment by XinnWang** [comment]
Thanks so much !

**Comment by fightmoney** [comment]
@XinnWang Can you tell me how to download it?

**Comment by xushangnjlh** [comment]
> > @RupertPaoZ Same problem here. Have you found the dataset ?
> 
> `Bovisa_2008-09-01-FRONTAL`

It contains 29346 images, which is not consistent with the number (10k) in the paper?
