### ISSUE TITLE
How long did it take to train the vocabulary?

### ISSUE THREAD

**Issue by RupertPaoZ** [raulmur/ORB_SLAM2#1014]
I am training it on the same dataset and I wonder how long will it take?

**Comment by fightmoney** [comment]
Hi Bro,
I am doing the same thing now. Can I ask you some question?

**Comment by RupertPaoZ** [comment]
> Hi Bro, I am doing the same thing now. Can I ask you some question?

Of course, you can send your questions to my email(bzb@zju.edu.cn), but I'm not sure if I can answer yours.
