### ISSUE TITLE
Trade performance for Accuracy

### ISSUE THREAD

**Issue by drewsipher** [raulmur/ORB_SLAM2#130]
Hey there,
I'm super impressed by all the work you've done. The library is great. 

I did have a question though; Is there any way to improve accuracy, even if it's at the cost of performance. I am running pre-recorded samples, and I need the highest accuracy for localization possible. Looped samples work very well of course so we try to produce those as much as possible. The samples are 640x480. Would higher resolutions help? How much can I affect accuracy with the number of features or other parameters? Are there parameters for increasing the iterations or threshold size for local or global BA?

Thank you for any information you can share.

**Comment by AlejandroSilvestri** [comment]
Hi,

Yes, higher resolution improve accuracy.

More keyframes help.  One way is messing the code to produce more keyframes, another is playing the video forward and backward many times on some spot in need, new keyframes will appear.

In Optimizer::LocalBundleAdjustment you can increase number of iterations and reduce threshold.  Optionally, you cam replace Local BA by Global BA, which will work slower as the map growth.

**Comment by drewsipher** [comment]
Hey Alejandro,
Thanks for the suggestions. Unfortunately I'm not using Orb SLAM anymore so I'm going to close this issue.

**Comment by haithink** [comment]
@drewsipher  So now which system are you using ?
