### ISSUE TITLE
A question about aligning the keyframe trajectories with ground truth

### ISSUE THREAD

**Issue by hwb0314** [raulmur/ORB_SLAM2#133]
@raulmur 
Dear Mur-Artal:

Recently I've read your paper "ORB-SLAM: A Versatile and Accurate Monocular SLAM System", in which you get impressive results compared with other state-of-art SLAM systems. I want to say thank you for your work.

However, here is a problem troubling me for a long time. In the section VIII. EXPERIMENTS, B. Localization Accuracy in the TUM RGB-D Benchmark, you mention that in order to compare trajectory with the ground truth, you align the keyframe trajectories using a similarity transformation, as scale is unknown, and measure the absolute trajectory error. 

I want to wander what exact similarity transformation you used, may I just change the scale of the trajectories to get a minimal absolute trajectory error? I use the "evaluate_ate.py" script, one of  which automated evaluation tool published by TUM ( "A Benchmark for the Evaluation of RGB-D SLAM Systems", web: http://vision.in.tum.de/data/datasets/rgbd-dataset/tools#evaluation ), to caculate the ATE. When I change the scale factor, I get different RMSE. 

For example, I use ORB-SLAM2 to get a trajectory of fr3_long_office. When setting the scale factor to 1.0, I get RMSE=122.37cm, however I get RMSE=1.6cm with scale=2.45, which better than your result(RMSE=3.45cm) of your paper. Is it right for me to change the scale factory to get a minimal ATE for every database sequence? Or should I fixed the scale factory of the sequences captured by the same camera? 

Thanks again for your reading my email. I do appreciate your generous sharing. And have a nice day! Looking forward to your reply.

![fr3_long_office_mono_trajector_ate__scale_2 45_rmse_1 6cm](https://cloud.githubusercontent.com/assets/15951600/17169122/9453bae0-5418-11e6-8dd4-9b0af979cca8.png)

![fr3_long_office_mono_trajector_ate_scale_1_rmse_122cm](https://cloud.githubusercontent.com/assets/15951600/17169178/d4085902-5418-11e6-822e-4c4b287c9118.png)

**Comment by marcusvgomez** [comment]
Did you get any response to this?

**Comment by raulmur** [comment]
https://github.com/raulmur/evaluate_ate_scale
