### ISSUE TITLE
Final Segmentation fault  ~ is that OK?

### ISSUE THREAD

**Issue by jiapei100** [raulmur/ORB_SLAM2#135]
ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Camera Parameters: 
- fx: 517.306
- fy: 516.469
- cx: 318.643
- cy: 255.314
- k1: 0.262383
- k2: -0.953104
- k3: 1.16331
- p1: -0.005358
- p2: 0.002628
- fps: 30
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

-------
Start processing sequence ...
Images in the sequence: 756

init done
opengl support available
New Map created with 76 points
Wrong initialization, reseting...
System Reseting
Reseting Local Mapper... done
Reseting Loop Closing... done
Reseting Database... done
New Map created with 128 points
-------

median tracking time: 0.0204959
mean tracking time: 0.0219218

Saving keyframe trajectory to KeyFrameTrajectory.txt ...

trajectory saved!
QObject::~QObject: Timers cannot be stopped from another thread
Segmentation fault (core dumped)

**Comment by jiapei100** [comment]
No idea how I figure this issue... But now, all problems gone....

Cheers

**Comment by shjtdxmhy** [comment]
How did you solve this problem?

**Comment by AnthonyChuah** [comment]
I got this problem as well: anyone have any idea how this was solved?

**Comment by JiankaiSun-SJTU-MVIG-training** [comment]
I also got this problem :(

**Comment by cvDreamer** [comment]
I got the same problem, any solution?

**Comment by ghost** [comment]
Compile with debug run
gdb --args yourbinary parameters
then enter
run
In the gdb console.
When it crashes, enter
where
and you will see the source of the problem

**Comment by melodybinbin** [comment]
https://github.com/raulmur/ORB_SLAM2/issues/547

**Comment by melodybinbin** [comment]
https://github.com/raulmur/ORB_SLAM2/issues/547
You can try this. However, I have not solved it throuth the old version of Pangolin at https://github.com/stevenlovegrove/Pangolin/tree/8b8b7b96adcf58ac2755dedd3f681fc512385af0

**Comment by shenlan1994** [comment]
Try to remove CMakeLists.txt "march=native" Optimization options，It may be help for you .

**Comment by YangZhouDL** [comment]
Do you mean this record"QObject::~QObject: Timers cannot be stopped from another thread" does not have any influence since the trajectory has been saved?

**Comment by nickxiang0306** [comment]
https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/452 maybe this issue could help you fix this segfault bug. And I met the bug when running orb-slam3.
