### ISSUE TITLE
stereo frame constructor code cause crash in extreme condition

### ISSUE THREAD

**Issue by flankechen** [raulmur/ORB_SLAM2#162]
in frame.cc line 83 to 86
```
    if(mvKeys.empty())
        return;

N = mvKeys.size();
```
if key points is empty, return and N is leave uninitialized, and maybe some positive integer due to the environment.
In extreme conditions, tracking lost soon after initialization(few key frame), if the very next frame's N is uninitialized and large, it will goes in `Tracking::StereoInitialization()` which would cause a crash in `MapPoint::AddObservation(KeyFrame* pKF, size_t idx)`

moreover, in other constructors, like RGBD and mono only gray way, N is handled before return,
line 135 to 141
```
    // ORB extraction
    ExtractORB(0,imGray);

    N = mvKeys.size();

    if(mvKeys.empty())
return;
```

**Comment by raulmur** [comment]
You found a bug :)
I will merge some updates into the master branch soon and I will also include this fix.
Thanks!
