### ISSUE TITLE
Multi-camera SLAM based on ORB-SLAM2

### ISSUE THREAD

**Issue by urbste** [raulmur/ORB_SLAM2#165]
Hey,

I developed a Multi-camera SLAM based on ORB-SLAM2.
It is dubbed MultiCol-SLAM and if you are interested you can find it here: https://github.com/urbste/MultiCol-SLAM

It works with and arbitrary number of rigidly coupled, central cameras (fisheye, perspective, omni).

Cheers :-)
Steffen

**Comment by poine** [comment]
Hi Steffen

It looks awesome. I have not looked in your code yet, but I watched your
demo video and I am amazed. I am looking forward to reading your paper.

Poine

**Comment by geokarant** [comment]
Really good work Urbste! Did you test it with a  monocular RGB camera? or even on real-time examples??
