### ISSUE TITLE
Map Viewer Top View

### ISSUE THREAD

**Issue by dk683** [raulmur/ORB_SLAM2#17]
Hello, for the Map Viewer, would there be a way to set the view as Top View, like this video (https://www.youtube.com/watch?feature=player_embedded&v=LnbAI-o7YHk)?
Thank you for your help!

**Comment by marcelinomalmeidan** [comment]
I change the view using the three buttons of my mouse. Ends up being intuitive to use! ;-)

**Comment by marcelinomalmeidan** [comment]
Also, I guess you can change the viewer parameters in the .yaml file you are using (the following is in the TUM1.yaml):
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

**Comment by dk683** [comment]
Hello @marcelinomalmeidan! Modifying the Viewer.Viewpoint* parameters in *.yaml did the trick!
Thank you for your help!
:+1: :+1:

**Comment by LinHuican** [comment]
dd

**Comment by LinHuican** [comment]
@marcelinomalmeidan @dk683 Current Frame work well, while the map viewer cannot, any advices?

Thank you for your help!

**Comment by dk683** [comment]
Hello @LinHuican. I am sorry. I could not understand your question.
Could you be more specific?! :-)

**Comment by LinHuican** [comment]
Hi, Thank you for you attention.@dk683. I run monocular examples on ubuntu 12.04, and the  "Current Frame" window work as expected, while the "Map Viewer" Window just black, not working.
Thank you for your help!

**Comment by dk683** [comment]
Hmm ... that is strange. Could you double check you installed everything (including prerequisites) correctly?

Additionally, are you running the TUM dataset or KITTI dataset example?
Also, are you running the ROS  monocular version?

**Comment by LinHuican** [comment]
Yes, so strange. I cannot install libtiff5-dev, which is optional dependencies for video input of Pangolin, I install libtiff4 instead. (When I try to remove libtiff4 to install libtiff5-dev, I broke the ubuntu. )
I am running the TUM dataset example, without ROS.

Now, I install ubuntu 14.04.3, and the problem is missing.

Thank you very much!!!

**Comment by dk683** [comment]
I am glad to hear! :D

**Comment by zzzzzq** [comment]
@dk683 @LinHuican Hello！Sorry to bother you, but I met the same question as @LinHuican ,Current frame works well but Map Viewer is all black. I tried to solve this for days but I failed....I have installed all dependencies and I use ROS indigo with xtion depth camera.

**Comment by LinHuican** [comment]
Hello @zzzzzq, your ubuntu version is 12.04? Well, when I installed ubuntu 14.04, the problem was missing. So I am sorry to say I cannot help, and if you can solve the problem, could you please share it?

**Comment by zzzzzq** [comment]
@LinHuican Thank you! But my version is 14.04......I have reinstalled it sever times but it doesn't work...maybe I should consider some other slam software

**Comment by zhw5772** [comment]
@zzzzzq  Have you solved the problem? I met the same problem.
14.04,the map viewer is black.
If you can solve is, could you please share it?

**Comment by zzzzzq** [comment]
@zhw5772 I vaguely remember it was because I didn't install Pangolin correctly.

**Comment by zhw5772** [comment]
@zzzzzq  Thank you!
I have re-installed Pangolin for many times.
The map viewer still did not work.
I am going crazy...

**Comment by zzzzzq** [comment]
@zhw5772 May be you should try to delete build/ file and recompile it or you can find another way to test if your Pangolin is installed correctly
