### ISSUE TITLE
ORB Slam2

### ISSUE THREAD

**Issue by venkataramanas1** [raulmur/ORB_SLAM2#185]
Hi all ,

I  have built  ORB Slam2 project , the open source code and the output is not deterministic .  It gives random output for every iteration.

Is it because of random functions that are used ?  . Can you guys help me to fix this by guiding me to identify potential functions which may cause random behaviour.

**Comment by AlejandroSilvestri** [comment]
RANSAC uses random variables.  And RANSAC is used in many methods in orb-slam2.

I don't think making a deterministic orb-slam is a good idea.

**Comment by mojovski** [comment]
@AlejandroSilvestri  depends :) a fixed seed would help to evaluate the quality in continuous benchmarks.

**Comment by venkataramanas1** [comment]
thanks for the reply

**Comment by AlejandroSilvestri** [comment]
@mojovski, you are right!

I'm not sure if doing so is an easy or near impossible task, but it worth trying, or at least looking for RANSAC in orb-slam2 and g2o.
