### ISSUE TITLE
Pangolin (?) Issues with ORB SLAM (Ubuntu 16.04)

### ISSUE THREAD

**Issue by passion-creativity-enthusiasm** [raulmur/ORB_SLAM2#201]
Hi enthusiasts,

I have an issue with ORB SLAM non-ros version in recent days that really was frustrating. I am running on Ubuntu 16.04 with Nvidia GTX950 card and using OpenCV v2.4.13. 

For some reason whenever I run my ORB SLAM with a dataset of 17545 files, the system will hang abruptly citing **segmentation fault (core dump)**. There is an initial message stating, "**Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.**"

I have followed the instructions as kindly written in the documentation and previously I have setup ORB SLAM to run smoothly in Ubuntu 14.04 with an AMD card.

![problem_pangolin](https://cloud.githubusercontent.com/assets/6077015/20612236/b1ce6546-b2f2-11e6-8ed9-7abe0d569f55.png)

![problem_pangolin_2](https://cloud.githubusercontent.com/assets/6077015/20612247/c91a2a46-b2f2-11e6-8155-0b5d485381d8.png)

**Comment by passion-creativity-enthusiasm** [comment]
In case anyone encounter this problem again, unfortunately, it can be resolved by re-installing in Ubuntu 14.04 :)

Thanks all!

**Comment by edgar-explorer** [comment]
I encounter the same issue, can it be solved except re-installing ubuntu

**Comment by xujinjinjinjin** [comment]
I encounter the same issue with ORB SLAM ros version,can it be solved except re-installing ubuntu？

**Comment by xujinjinjinjin** [comment]
> I encounter the same issue with ORB SLAM ros version,can it be solved except re-installing ubuntu？

I bypassed it by going in the g2o cmakelists and the orb slam cmakelists and removing -march=native .yeah~
