### ISSUE TITLE
System shutdown without viewer

### ISSUE THREAD

**Issue by caselitz** [raulmur/ORB_SLAM2#229]
Hi Raul,

in a recent commit you made the viewer optional. I think you forgot to completely adapt the System::Shutdown() accordingly. Without viewer

1) you can get a segfault when checking the while condition
2) the pangolin::BindToContext complains "MakeCurrent: Not available with non-pangolin window."

Maybe you can fix this in your next commit.

Thanks,
Tim

**Comment by raulmur** [comment]
Fixed. Thanks!
