### ISSUE TITLE
Crash bug, easy fix, in FrameDrawer::DrawFrame, attribute N changes asynchronously.

### ISSUE THREAD

**Issue by AlejandroSilvestri** [raulmur/ORB_SLAM2#236]
https://github.com/raulmur/ORB_SLAM2/blob/master/src/FrameDrawer.cc#L94

N, many vector size, is not properly copied in mutex, so sometimes FrameDrawer::Update changes it while processing FrameDrawer::DrawFrame.  When N incresase its value, a Seg Fault is possible, and it happens!  That's how I found it while debugging.

Simply replace `N` with `mapPoints.size()`, or make a safe copy of N in mutex.

**Comment by raulmur** [comment]
I have fixed it. Thanks!
