### ISSUE TITLE
Has anyone had successfully Pangolin working on iOS ?

### ISSUE THREAD

**Issue by hoverpeter** [raulmur/ORB_SLAM2#237]
I made a simple iOS App that builds on the core engine, but still missing graphics module.

**Comment by pmoulon** [comment]
Nice,
Not sure that you can publish your code under MIT license since ORB_SLAM is GPL...

**Comment by hoverpeter** [comment]
@pmoulon thanks. I apologize. I'll make changes upon your comment. Any guidance?

**Comment by pmoulon** [comment]
No worries.
You must use the same license as the original project
You must include this file https://github.com/raulmur/ORB_SLAM2/blob/master/License-gpl.txt
And you can add another file explaining the goal of your project as it is done here https://github.com/raulmur/ORB_SLAM2/blob/master/LICENSE.txt

FYI.
https://choosealicense.com/licenses/ 
GNU GPLv3 => Condition => Same License
