### ISSUE TITLE
Comparing 6DOF results and ground truth of EuRoC dataset

### ISSUE THREAD

**Issue by Oranjo** [raulmur/ORB_SLAM2#253]
Hi

I'm sorry to ask a basic question, but How can I compare the result(CameraTrajectory.txt) and the ground truth in EuRoC dataset? I'm currently trying V101, V201.
The position result shows similar pattern to the ground truth, but can't be directly compared with. It seems to require transformation matrix.
The camera pose result is quite different from the ground truth. I transformed quaternion to Euler angle and It does not seem to match the reference; especially roll and pitch angles are not.

How can I make 6DOF error graph?

Thanks.

**Comment by pigbreeder** [comment]
Hi @Oranjo .
Do you solve the problem?  
Do you know how to compare the result and the ground truth in KITTI dataset?

Thanks.

**Comment by Oranjo** [comment]
Hi.
I could compare the results with this(
https://github.com/raulmur/evaluate_ate_scale)
But the results are not the same as paper.
I referred to this issue that you've already checked:
https://github.com/raulmur/ORB_SLAM2/issues/270

Thanks.
ᐧ


-------------------------------------------------------------------------

석사과정 김연조 / 지능형항법제어연구실

건국대학교 항공우주정보시스템공학과

서울특별시 광진구 능동로 120  건국대학교 신공학관 502호

Tel : 02-452-4176, H.P : 010-8851-2610

2017-06-21 20:50 GMT+09:00 pigbreeder <notifications@github.com>:

**Comment by pigbreeder** [comment]
Thank you for your kind reply.
But when I use the command(./evaluate_ate_scale.py CameraTrajectory.txt V1_01_easy/mav0/state_groundtruth_estimate0/data.csv )
,it print Couldn't find matching timestamp pairs between groundtruth and estimated trajectory!
Where did i make mistake?

**Comment by Oranjo** [comment]
Hi

I followed the instruction of original tool as the readme file says. (
http://vision.in.tum.de/data/datasets/rgbd-dataset/tools#evaluation)

I think it can be helpful for you. I'm sorry that I can't tell you in
detail cause I'm quite busy recently....


Best regards.


ᐧ


-------------------------------------------------------------------------

석사과정 김연조 / 지능형항법제어연구실

건국대학교 항공우주정보시스템공학과

서울특별시 광진구 능동로 120  건국대학교 신공학관 502호

Tel : 02-452-4176, H.P : 010-8851-2610

2017-06-22 16:00 GMT+09:00 pigbreeder <notifications@github.com>:
