### ISSUE TITLE
Compilation issues on Mac OS X 

### ISSUE THREAD

**Issue by keshavchintamani** [raulmur/ORB_SLAM2#255]
I've tried unsuccessfully to build OrbSlam2 on Mac OSX. I have gcc/g++ 6 installed and all dependencies through Homebrew. 

The first problem is usleep() which I read is a posix specific routine (?).  Inserting #include <unistd.h> fixes that. 

The second problem is that the default ./build.sh script is invoking CMAKE with vanilla options. So Clang is being called despite cmake flags checking for C++11 support. Maybe Clang supports C++11 but it still throws errors. I'm no CMAKE expert, but forced the script to use g++-6 by replacing

`cmake ..  -DCMAKE_BUILD_TYPE=Release` 

with 

`cmake .. -DCMAKE_C_COMPILER=/usr/local/Cellar/gcc/6.1.0_1/bin/gcc-6 -DCMAKE_    CXX_COMPILER=/usr/local/Cellar/gcc/6.1.0_1/bin/g++-6 -DCMAKE_BUILD_TYPE=Release` 

Both the g2o and DBoW2 libs compile fine but I cannot get LibOrbSlam2 to generate:

```
-- Generating done
-- Build files have been written to: /Users/kchintamani/sandbox/slam_workspace/ORB_SLAM2/build
make[2]: *** No rule to make target `../Thirdparty/DBoW2/lib/libDBoW2.so', needed by `../lib/libORB_SLAM2.dylib'.  Stop.
make[1]: *** [CMakeFiles/ORB_SLAM2.dir/all] Error 2
make: *** [all] Error 2
```
Any thoughts are welcome!

**Comment by gsabran** [comment]
I think that OSX creates `.dylib` instead of `.so`, so there's no `../Thirdparty/DBoW2/lib/libDBoW2.so` but a `../Thirdparty/DBoW2/lib/libDBoW2.dylib`
Not sure yet how to fix it though
