### ISSUE TITLE
New Semi-Dense Reconstruction

### ISSUE THREAD

**Issue by sunstarchan** [raulmur/ORB_SLAM2#26]
Hi @raulmur 

On your project page, you said new semi-dense reconstructing was able to run. But in this github source base, I didn't find any part handle semi-dense reconstruction. That's right?

**Comment by gitunit** [comment]
not released yet. have a look [here](https://github.com/raulmur/ORB_SLAM/issues/46)

**Comment by sunstarchan** [comment]
Got it. Thanks
