### ISSUE TITLE
Running Issue ?

### ISSUE THREAD

**Issue by gs14iitbbs** [raulmur/ORB_SLAM2#265]
I have installed all the dependencies and the ORB_SLAM2.

I tried executing the following:
-------------------------------------------------------------------------------------------------------------
#5. Stereo Examples

## KITTI Dataset

1. Download the dataset (grayscale images) from http://www.cvlibs.net/datasets/kitti/eval_odometry.php 
chmod +x build.sh
./build.sh
2. Execute the following command. Change `KITTIX.yaml`to KITTI00-02.yaml, KITTI03.yaml or KITTI04-12.yaml for sequence 0 to 2, 3, and 4 to 12 respectively. Change `PATH_TO_DATASET_FOLDER` to the uncompressed dataset folder. Change `SEQUENCE_NUMBER` to 00, 01, 02,.., 11. 
```
./Examples/Stereo/stereo_kitti Vocabulary/ORBvoc.txt Examples/Stereo/KITTIX.yaml PATH_TO_DATASET_FOLDER/dataset/sequences/SEQUENCE_NUMBER
```
-------------------------------------------------------------------------------------------------------------

But when I execute the command : 

Workstation:~/ORB_SLAM2$ sudo ./Examples/Stereo/stereo_kitti Vocabulary/ORBvoc.txt Examples/Stereo/KITTI00-02.yaml /home/gaurav/Downloads/data_odometry_gray/dataset/sequences/00
-------------------------------------------------------------------------------------------------------------
IT shows no response, neither any error..etc.
-------------------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------------
So what could be the problem ?

**Comment by iDonghq** [comment]
Have you solved this problem? I have run the same one
