### ISSUE TITLE
Cannot compile Viewer.cc due to Pangolin

### ISSUE THREAD

**Issue by tdnet12434** [raulmur/ORB_SLAM2#27]
Scanning dependencies of target ORB_SLAM2
[  4%] [  8%] [ 13%] [ 17%] [ 21%] [ 26%] [ 30%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/System.cc.o
[ 34%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/LocalMapping.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Tracking.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/LoopClosing.cc.o
[ 39%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/ORBmatcher.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/ORBextractor.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/FrameDrawer.cc.o
[ 43%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Converter.cc.o
[ 47%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/KeyFrame.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/MapPoint.cc.o
[ 52%] [ 56%] [ 60%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Map.cc.o
[ 65%] [ 69%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/MapDrawer.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Optimizer.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/PnPsolver.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Frame.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/KeyFrameDatabase.cc.o
[ 73%] [ 78%] [ 82%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Viewer.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Sim3Solver.cc.o
Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Initializer.cc.o
/home/fx/Dropbox/catkin_ws/src/ORB_SLAM2/src/Viewer.cc: In member function ‘void ORB_SLAM2::Viewer::Run()’:
/home/fx/Dropbox/catkin_ws/src/ORB_SLAM2/src/Viewer.cc:58:5: error: ‘CreateWindowAndBind’ is not a member of ‘pangolin’
     pangolin::CreateWindowAndBind("ORB-SLAM2: Map Viewer",1024,768);
     ^
/home/fx/Dropbox/catkin_ws/src/ORB_SLAM2/src/Viewer.cc:134:9: error: ‘FinishFrame’ is not a member of ‘pangolin’
         pangolin::FinishFrame();
         ^

Thank you advance :)

**Comment by tdnet12434** [comment]
Just edit 
find_package(Pangolin REQUIRED)
to
find_package(Pangolin 0.2 REQUIRED)
My problem solved

**Comment by aicioara** [comment]
Since this is nicely indexed on Google when looking for `CreateGlutWindowAndBind`, I'll write my solution here as well, although it is a bit offtopic.

As of version `v0.3` the function is called `CreateWindowAndBind` (as the issue author states). In older versions it used to be called `CreateGlutWindowAndBind`.
