### ISSUE TITLE
A question about recover 8 motion hypotheses when initializer

### ISSUE THREAD

**Issue by myBestLove** [raulmur/ORB_SLAM2#289]
First thanks for your work.

I read the code about recover 8 motion hypotheses  when slam initialization, I did not understand in line 639-642 in initializer.cc.   I read the Motion and structure from motion in a piecewise planar environment, it said t'=(d1-d3)(x1 0 -x3)    t' = (d3-d1)n' .  so  I considered the n' should be (-x1 0 x3).

but I see the code is        
        cv::Mat np(3,1,CV_32F);
        np.at<float>(0)=x1[i];
        np.at<float>(1)=0;
        np.at<float>(2)=x3[i];

Is there any problem?  thanks

**Comment by AlejandroSilvestri** [comment]
@myBestLove 

[Initializer.cc line 639](https://github.com/raulmur/ORB_SLAM2/blob/master/src/Initializer.cc#L639)

[ Motion and structure from motion in a piecewise planar environment](https://hal.archives-ouvertes.fr/inria-00075698/document)

Well noted, equation (14) in the paper and forward, for d'=d2,  n'=(x1, 0, -x3)

I believe this is a bug, line 642 should be `np.at<float>(2)=-x3[i];` (note the minus sign).

I run it but didn't see any improvements in initialization.  If someone if interested in going further, it worth trying to initialize with images of planes, and echo on console which method orb-slam2, and specifically mention if d'=d2 or d'=-d2.

orb-slam2 has two initialization method, let's name them H and F (homography and fundamental matrix).  H has 8 possible solutions, this alleged bug affects 4 of them.
