### ISSUE TITLE
Performance problem in  mobile device 

### ISSUE THREAD

**Issue by ningduyanghe** [raulmur/ORB_SLAM2#290]
Hi,I am planning to use orb_slam2 in my AR app,but the performance in mobile device is not adequate at all(<5fps).I test PTAM in the same device,but it perform better(>20fps).I read your papers but I am not good at algorithm,so...I just can not accept the results because I like your beautiful codes.

**Comment by ningduyanghe** [comment]
btw,in ios and android,camera rotation can be read from motion sensors directly.

**Comment by AlejandroSilvestri** [comment]
@ningduyanghe , if you wan't to integrate motions sensors, you can do it with Kalman filter or something like that.  Not so straightforward.

But you must know visual slam is far more accurate than motion sensors.

ORB-SLAM couldn't perform well on mobile.  The firs goal is to obtain an acceptable performance in tracking only.

**Comment by ningduyanghe** [comment]
@AlejandroSilvestri You realy help me a lot!!!

**Comment by AlejandroSilvestri** [comment]
@ningduyanghe , my pleasure.
