### ISSUE TITLE
ORB computation code

### ISSUE THREAD

**Issue by agend** [raulmur/ORB_SLAM2#292]
Hi, I have noticed that ORB descriptor computation and matching algorithm is coded by you. What was the intentions ? Why not to use ORB from OpenCV?
Thx

**Comment by HongmouZhang** [comment]
Because the ORB feature detector in ORB_SLAM is different to OpenCV version. ORB_SLAM version segments the whole image to several grids, and try to get features from each grid. In this way, the feature detector can gets features which are widely distributed in the whole image
