### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc

### ISSUE THREAD

**Issue by suijingfeng** [raulmur/ORB_SLAM2#294]
hello, I'm a student from China, I successfully compile the ORB_SLAM2 as the read me, 
but I can not run it.
--------------------------------------------------------- 
Loading ORB Vocabulary. This could take a while...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
![screenshot from 2017-03-24 19-46-15](https://cloud.githubusercontent.com/assets/10341056/24279968/2de7141e-1088-11e7-8d90-447259704c65.png)
 the memory usage up to 99%, then core dumps, I don't know how to debug this, any helps? thanks.

**Comment by romanomatthew23** [comment]
Hello, I had the same issue. After removing ORB_SLAM2, and re-downloading and compiling it was fixed for me. No idea why but it is working now.

**Comment by l1va** [comment]
Had the same issue - found that i pass wrong path to Vocabulary. In such case should be an exception i think. (i run mono with ROS)

**Comment by joebedard** [comment]
I had the same problem. I was passing the vocabulary directory instead of the vocabulary file. Correct usage (for example mono_tum) is:
./mono_tum path_to_vocabulary_file path_to_settings_file path_to_sequence_dir
