### ISSUE TITLE
Using rectified Images

### ISSUE THREAD

**Issue by kilmarnock** [raulmur/ORB_SLAM2#30]
Hi!
Perhaps you can help me with this:

I use ros and have some bags with already undistorted, rectified images.

What parameters could I use to give ORB_SLAM2 a try (rectifying a second time, no problem, just want to see the results).

Thank you

**Comment by poine** [comment]
just use zero for Camera.k1

Tracking.cc line 1575
 DistCoef.at<float>(0) = fSettings["Camera.k1"];

line 422 in Frame.cc:
void Frame::UndistortKeyPoints()
{
    if(mDistCoef.at<float>(0)==0.0)
    {
        mvKeysUn=mvKeys;
        return;
    }
