### ISSUE TITLE
Not solved yet. Please help! How can I upload the camera data and apply monocular in real time?

### ISSUE THREAD

**Issue by scp096** [raulmur/ORB_SLAM2#312]
Hi,

I'm a newbie at SLAM and Linux system. I followed the tutorial and ran the example TUM dataset in Ubuntu for a test, it works well. Now I want to upload my camera raw data in real time to run monocular algorithm. How can I do this? Which interface should I choose?

And how can I make use of my telephone sensor to make a better adjustment?

Thanks a lot for your help.

**Comment by AlejandroSilvestri** [comment]
Hi, I don't believe you can use orb-slam2 in realtime in your phone hardware.  Not enough processing power.

Everybody is waiting for a slam method working in their phones.  LSD-SLAM is close enough, working only in tracking mode, slow, 2 or 3 frames per second.

**Comment by hoverpeter** [comment]
@AlejandroSilvestri I am able to make it run on iPhone. With some basic optimization, it can run avg. 15fps in full mode.

**Comment by hoverpeter** [comment]
I haven't made any effort to port LSD-SLAM to an iPhone. But I really want to. Is there any semi-useful materials out there as guidance?

**Comment by AlejandroSilvestri** [comment]
@hoverpeter 
orb-slam2 on iPhone?
That is awesome!
Can you describe your hardware processor?  Only to know the power.
What optimizations did you do?

**Comment by hoverpeter** [comment]
It was done on iPhone 7 which is powerful and also on an old iPad Mini, not so powerful but okay. 

Not so much. Started with some basic parallelization.

**Comment by hoverpeter** [comment]
@AlejandroSilvestri Could you possibly point me some useful material for porting LSD-SLAM?

**Comment by scp096** [comment]
@AlejandroSilvestri @hoverpeter , what about just uploading the camera raw data  to the local PC server when and let the server run it? Maybe I'm just too new to figure out something like a interface to do this.

**Comment by scp096** [comment]
@AlejandroSilvestri @hoverpeter , thanks for your guidance. what about just uploading the camera raw data to the local PC server when and let the server run it? Maybe I'm just too new to figure out something like a interface to do this.

**Comment by AlejandroSilvestri** [comment]
@scp096 , it is doable.  Actually some students in my class did something like that.  It was a quick and dirty process, I advice against it :)

They took pictures with the phone, with an app that send them to a node.js server, which resend it through some ros plugin to the actual orb-slam2 application in the same server.

It worked, they were looking to relocalize on each image.  Next step will be streaming video.

**Comment by scp096** [comment]
@AlejandroSilvestri .Thanks a lot. I took picture and sent every frame to the server and and after some encoding operation I  published  it to the topic. It works for me too. Now I close this issue page.

**Comment by mslavescu** [comment]
@AlejandroSilvestri on Android your students could use something like:

https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en

That provides very fast photo or video live streaming over WiFi.

And then use a simple Python OpenCV script to read the live network video stream and publish the frames on ROS network, something like this:

https://github.com/OSSDC/self-driving-car-1/blob/master/docker-instance-scripts/ros_feature_detectio_publisher.py

**Comment by AlejandroSilvestri** [comment]
@mslavescu , thank you!

**Comment by scp096** [comment]
@mslavescu That's what I did!!

**Comment by kunyuwang** [comment]
@hoverpeter Is it possible to share what you did about the basic parallelization to make the orb-slam2 run 15 fps on iPhone 7 or iPad mini.

**Comment by kunyuwang** [comment]
Thanks.
