### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mojovski** [raulmur/ORB_SLAM2#36]
Very strange one. 
I am getting
```
make[2]: *** No rule to make target '/usr/lib/libOpenNI2.so', needed by '../lib/libORB_SLAM2.so'.  Stop.
```
but I dont see in any of the CMakeLists.txt files that OpenNI2 is referenced somewhere.
I searched the full project directory tree for it.

When the lib ORB_SLAM2 is defined here
https://github.com/raulmur/ORB_SLAM2/blob/master/CMakeLists.txt#L66
there is no clueabout OpenNI.

Any ideas?

May it come from Pangolin?

**Comment by gaoxiang12** [comment]
I guess it may come from Experiments

**Comment by mojovski** [comment]
Solved. The issue was inside pangolin. Had to remove the openni stuff from there
