### ISSUE TITLE
I have modified the algorithm a bit, but the result is different each time. Why?

### ISSUE THREAD

**Issue by hyunhoJeon** [raulmur/ORB_SLAM2#392]
I modified the code to use some of the features obtained through the ORB detector. 

As a result, the results obtained each time are very different. 

I think that a little change can exist by initialization. But this is too big. Why is this?

Ignore the blue color.

![11](https://user-images.githubusercontent.com/29697700/28511157-d3b84f94-7086-11e7-8f54-476d6048685a.png)
![22](https://user-images.githubusercontent.com/29697700/28511159-d6b23340-7086-11e7-993f-6f9cf5af45f9.png)

**Comment by AlejandroSilvestri** [comment]
@hyunhoJeon 

What are you showing to us?  Please explain with detail.
