### ISSUE TITLE
Run time hung?  (for help)

### ISSUE THREAD

**Issue by iDonghq** [raulmur/ORB_SLAM2#396]
when I execute the command :
  ./Examples/Stereo/stereo_kitti Vocabulary/ORBvoc.txt Examples/Stereo/KITTI00-02.yaml /home/gaurav/Downloads/data_odometry_gray/dataset/sequences/00

it shows no response, neither any error..etc.

**Comment by iDonghq** [comment]
sorry ! a stupid question!

**Comment by tejus-gupta** [comment]
Hi, I am facing the problem now. How did you handle it?
