### ISSUE TITLE
SO3 Lie Group?

### ISSUE THREAD

**Issue by bitchenxu** [raulmur/ORB_SLAM2#44]
does the orb slam 2 use the lie group ? in Loop closure?

**Comment by poine** [comment]
I am not sure to fully understand your question but your answer might be
in: http://europa.informatik.uni-freiburg.de/files/kuemmerle11icra.pdf
So... looks like yes, g2o uses an error parametrization to get avoid
singularities in rotations.

**Comment by bitchenxu** [comment]
i have found it in the paper.
