### ISSUE TITLE
[The magic number 60] Viewing angle must be less than 60 deg

### ISSUE THREAD

**Issue by MiaoDX** [raulmur/ORB_SLAM2#449]
Hi,
thanks for this great project, one interesting thing comes to me when looking at the codes, there are some code snippets in `ORBmatcher.cc`. Like [#L351](https://github.com/raulmur/ORB_SLAM2/blob/master/src/ORBmatcher.cc#L351) and [#L881](https://github.com/raulmur/ORB_SLAM2/blob/master/src/ORBmatcher.cc#L881) and [#L1039](https://github.com/raulmur/ORB_SLAM2/blob/master/src/ORBmatcher.cc#L1039), all mentioned the `Viewing angle must be less than 60 deg`, my problem is simple, is there any theoretical constraint on this specific number or it is just a common sense or  empirical knowledge?

Looking forward for your reply!

**Comment by AlejandroSilvestri** [comment]
@MiaoDX ,

It's empirical.

That condition aims to reduce mismatched fuses.
