### ISSUE TITLE
No output when I try to run Monocular Examples with TUM Dataset

### ISSUE THREAD

**Issue by ymd1012** [raulmur/ORB_SLAM2#466]
![_013](https://user-images.githubusercontent.com/25838459/32533733-6e0ea89c-c495-11e7-8390-3c012d37ef40.png)
I am new with SLAM so I don’t  know why it comes out and how to fix it either.
Could you please tell me what is meaning by the last sentence *Usage: ./mono_tum path_to_vocabulary path_to_settings path_to_sequence*?
Thank you very much

**Comment by jvhoven** [comment]
```./Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt ./Examples/Monocular/TUM1.yaml /home/yan/ORB_SLAM2/rgbd_dataset_freiburg1_xyz```

I think you forgot to add a space after specifying the configuration; `...TUM1.yaml/home/yan/...`.

**Comment by ymd1012** [comment]
Thank you for your reply!

发送自 Windows 10 版邮件应用

发件人: Jeffrey van Hoven
发送时间: 2017年11月8日 18:24
收件人: raulmur/ORB_SLAM2
抄送: ymd1012; Author
主题: Re: [raulmur/ORB_SLAM2] No output when I try to run MonocularExamples with TUM Dataset (#466)

./Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt ./Examples/Monocular/TUM1.yaml /home/yan/ORB_SLAM2/rgbd_dataset_freiburg1_xyz
I think you forgot to add a space after specifying the configuration; ...TUM1.yaml/home/yan/....
