### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by kamel271** [raulmur/ORB_SLAM2#480]
I am new with SLAM so  could you please tell me what is the meaning of this output 
Usage: rosrun ORB_SLAM2 Mono path_to_vocabulary path_to_settings i get this when ever i run this command rosrun ORB_SLAM2 Mono Vocabulary/ORBvoc.txt Examples/Monoculer/EuRoC.yaml true
![screenshot from 2017-11-30 16 18 14](https://user-images.githubusercontent.com/19622084/33455469-2bcf5434-d5ea-11e7-99be-bf550599c33c.png)

**Comment by lfrschkn** [comment]
hi
this is a message showing you how to use the examples
it is telling you to structure your command as:
rosrun ORB_SLAM2 Mono path_to_vocabulary path_to_settings

you basically did that but I think you have got the path_to_settings wrong
you have: Examples/Monoculer/...
it should be: Examples/Monocular/...

further why do you put a true at the end? I do not think that this belongs there

**Comment by kamel271** [comment]
thank you for the answer  lfrschkn  
after i corrected that mistake i got this errors  
![screenshot from 2017-12-01 08 36 07](https://user-images.githubusercontent.com/19622084/33485134-47d580b6-d673-11e7-9645-dfe9c83fd7e4.png)

**Comment by lfrschkn** [comment]
refer to [#186](https://github.com/raulmur/ORB_SLAM2/issues/186)
