### ISSUE TITLE
Pangolin Error + plus ERROR: Calibration parameters to rectify stereo are missing!

### ISSUE THREAD

**Issue by Exception4U** [raulmur/ORB_SLAM2#49]
I am trying to run ORB_SLAM2 on kitti_04.bag sequence with following command

$ rosrun ORB_SLAM2 Stereo Vocabulary/ORBvoc.txt Examples/Stereo/KITTI04-12.yaml false

$ rosbag play --pause kitti_04.bag /kitti_stereo/left/image_rect:=/camera/left/image_raw /kitti_stereo/right/image_rect:=/camera/right/image_raw

error I faced is ..............

ERROR: Calibration parameters to rectify stereo are missing!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Pangolin X11: Unable to retrieve framebuffer options
Aborted (core dumped)

**Comment by raulmur** [comment]
I fixed the bug: https://github.com/raulmur/ORB_SLAM2/commit/27eaac571e8c7e9c7eaf7986c0a336cc107571b6
Thanks!!
