### ISSUE TITLE
Fail to build ROS - Undefined reference pointing to ZED camera libraries.

### ISSUE THREAD

**Issue by InigoCastro** [raulmur/ORB_SLAM2#514]
Hello everyone,

I am currently trying to build the ROS Example in ORB SLAM 2 by running the file build_ros.h. I have already sucessfully built ORB SLAM 2 and run some examples without problems. However, when trying to build the ROS examples, the following is prompted in the terminal:

[ 55%] Building CXX object CMakeFiles/MonoAR.dir/src/AR/ViewerAR.cc.o
[ 66%] Linking CXX executable ../Mono
**//usr/local/zed/lib/libsl_core.so: undefined reference to nppiFree
//usr/local/zed/lib/libsl_core.so: undefined reference to nppiMalloc_32f_C1**
collect2: error: ld returned 1 exit status
CMakeFiles/Mono.dir/build.make:218: recipe for target '../Mono' failed
make[2]: *** [../Mono] Error 1
CMakeFiles/Makefile2:718: recipe for target 'CMakeFiles/Mono.dir/all' failed
make[1]: *** [CMakeFiles/Mono.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 77%] Linking CXX executable ../MonoAR
[ 88%] Linking CXX executable ../Stereo
**//usr/local/zed/lib/libsl_core.so: undefined reference to nppiFree
//usr/local/zed/lib/libsl_core.so: undefined reference to nppiMalloc_32f_C1**
collect2: error: ld returned 1 exit status
CMakeFiles/MonoAR.dir/build.make:300: recipe for target '../MonoAR' failed
make[2]: *** [../MonoAR] Error 1
CMakeFiles/Makefile2:820: recipe for target 'CMakeFiles/MonoAR.dir/all' failed
make[1]: *** [CMakeFiles/MonoAR.dir/all] Error 2
**//usr/local/zed/lib/libsl_core.so: undefined reference to nppiFree**
**//usr/local/zed/lib/libsl_core.so: undefined reference to nppiMalloc_32f_C1**
collect2: error: ld returned 1 exit status
CMakeFiles/Stereo.dir/build.make:218: recipe for target '../Stereo' failed
make[2]: *** [../Stereo] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/Stereo.dir/all' failed
make[1]: *** [CMakeFiles/Stereo.dir/all] Error 2
[100%] Linking CXX executable ../RGBD
**//usr/local/zed/lib/libsl_core.so: undefined reference to nppiFree
//usr/local/zed/lib/libsl_core.so: undefined reference to nppiMalloc_32f_C1**
collect2: error: ld returned 1 exit status
CMakeFiles/RGBD.dir/build.make:218: recipe for target '../RGBD' failed
make[2]: *** [../RGBD] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/RGBD.dir/all' failed
make[1]: *** [CMakeFiles/RGBD.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

It is a bit puzzling for me that somehow the ZED libraries show up here. It is  probably worth mentioning that I changed CMakelists.txt in the main ORB SLAM 2 directory to include the ZED libraries in order to run an application that uses ORB SLAM 2 and the camera. However, I have not changed the CMakeLists file that can be found in ORB_SLAM2/Examples/ROS/ORB_SLAM2. Therefore, I do no know when or how this conflict occurs and I have no clue on how to fix it.

Help on this issue would be appreciated.

System setup:

OpenCV: 3.2. and 3.4.
ZED camera SDK (software for developing applications with it): 2.2.1
NVIDIA CUDA: 9.1 and  9.0.

EDIT : A fresh rebuild of ORB SLAM 2 with the unchanged CMakeLists file solves this issue. However, the question now would be how to make this work even including the ZED libraries (or any library for that matter) so they do not conflict with building ROS Examples in ORB SLAM 2.

**Comment by abylikhsanov** [comment]
Can you tell me how did you fix it? I did not understand
