### ISSUE TITLE
Keyframe image numbers

### ISSUE THREAD

**Issue by DannyYCCheng** [raulmur/ORB_SLAM2#525]
Hi,

I have a stereo set up and my dataset is based on the KITTI data format. I am trying to figure out which images are keyframes, but am a bit lost. I looked at the SaveTrajectoryKITTI() function in System.cc and managed to save the poses of the keyframes, but unsure how to get the actual image numbers which are keyframes...?

Thanks in advance.

**Comment by pytholic** [comment]
@DannyYCCheng Did you figure this out? The `timestamps` saved by orbslam are not same as the input `timestamps`, so I am also lost.
