### ISSUE TITLE
ORB_SLAM2 how to generate Map or cloud point?

### ISSUE THREAD

**Issue by cdlwhm1217096231** [raulmur/ORB_SLAM2#533]
I want to generate cloud point by ORB_SLAM2? How to get it,please help me.

**Comment by siyuada** [comment]
You can pass the KeyFrame information to generate a pointcloud,like Tcw , rgb image , depth information.
Try this code,edited by gaoxiang(implemented in RGBD camera).
https://github.com/gaoxiang12/ORBSLAM2_with_pointcloud_map

**Comment by YomnaJehad** [comment]
@cdlwhm1217096231  did you find the solution?
@siyuada  i want to edit the stereo example code can you tell me which part in that modified code would help?
