### ISSUE TITLE
Is the map obtained from stereo configuration in true scale

### ISSUE THREAD

**Issue by ghost** [raulmur/ORB_SLAM2#548]
Hello Everyone,
I have used the ORB-SLAM2 and got a CameraTrajectory.txt file from the stereo case in EuRoC dataset. I would like to know, is the output from the stereo experiment in true scale or we need to calculate the scale with IMU integration.

Thank you.
Regards,
Dharma KC

**Comment by AlejandroSilvestri** [comment]
@dharma-kc 

The map is in true scale.  It takes the known distance between cameras as absolute scale reference.

**Comment by ghost** [comment]
@AlejandroSilvestri 
Thank you.
