### ISSUE TITLE
ORB SLAM 2 hangs after the frames gets over

### ISSUE THREAD

**Issue by nik13** [raulmur/ORB_SLAM2#572]
I have being using orb slam2 on TUM datasets. It starts normally but hangs after the images get over. I tested the same thing on my video, same behaviour. I have to kill the task to stop it.

I tried installing all the required libraries again, but it didn't help. 
Using Ubuntu 16.04

![screenshot from 2018-05-30 11-34-20](https://user-images.githubusercontent.com/8347993/40701963-99f1b582-63fd-11e8-8e53-2a0776c9a03b.png)

**Comment by weidongguo** [comment]
The frames are the inputs.
What do you expect when the program gets no more inputs? 
When the program has nothing to work with, it pauses and waits

Or I might not be understanding your question.

**Comment by nik13** [comment]
Its the same mono_tum program in examples. It do not stops. Just hangs when the frames are over.

**Comment by davide200294** [comment]
I've got the same error with the same dataset. Images are over, but ORB-SLAM has to do few more operations including save the KeyframeTrajectory.txt file so it should still run

**Comment by mayankamedhe** [comment]
@davide200294 But KeyframeTrajectory.txt file is not getting generated at all even after a long time since the last frame. 
Was anyone able to obtain the KeyframeTrajectory.txt file?

**Comment by mayankamedhe** [comment]
I solved the problem by referring to #547
