### ISSUE TITLE
usleep in LoopMapping and LoopClosing

### ISSUE THREAD

**Issue by connorsoohoo** [raulmur/ORB_SLAM2#616]
I noticed that in LoopMapping and in LoopClosing you have usleep calls for 3ms and 5ms respectively at the end of processing each frame. Is that just to handle scheduling the threads properly, or is there another purpose? Would I be able to increase performance by reducing the time period for these calls?

**Comment by gyubeomim** [comment]
@connorsoohoo 

Hello, Did you find out why using it??

please share it if you find out. 

thanks in advance :-)
