### ISSUE TITLE
cv::Mat * KeyFrame Operation 

### ISSUE THREAD

**Issue by connorsoohoo** [raulmur/ORB_SLAM2#620]
I dont understand what the cv::Mat * Keyframe operation means. 
For instance in System.cc, Line 429, you have.

`while(pKF->isBad())
{
    Trw = Trw*pKF-> mTcp;
    pKF = pKF->GetParent();
}`

Here Trw is a cv::Mat and pKF is a KeyFrame*

I know that the operation Trw * pKF should return a Keyframe * because mTcp is a variable within the KeyFrame class, but where is this overload operation defined where we can multiply a Mat and a KeyFrame? What does this operation even mean?

**Comment by yizhou-wang** [comment]
It should be a problem of operator precedence. 
```Trw = Trw*pKF-> mTcp;``` means ```Trw = Trw*(pKF-> mTcp);```

Please refer to https://en.cppreference.com/w/cpp/language/operator_precedence.
