### ISSUE TITLE
How to extract numeric values for position/translation and rotation from pose matrix?

### ISSUE THREAD

**Issue by salocinx** [raulmur/ORB_SLAM2#666]
Hi. I successfully compiled ORB_SLAM2. It runs very well. How do I have to extract the position and rotation values from the pose matrix `cv::Mat tcw` received from `TrackStereo()` function?

**Comment by DodsGTH94** [comment]
Hi @salocinx ,
I write you because I did like this: I printed out on the terminal the matrix easily using cout function. How did you do? How are the positions you get, in terms of accuracy?
Thanks

**Comment by salocinx** [comment]
Hi @DodsGTH94 , yes I found out about `std::cout << tcw << std::endl;` too 👍  You can access the elements of the matrix by doing so:

```
if(tcw.cols==4 && tcw.rows==4) {
    for(int y=0; y<tcw.rows; y++) {
        for(int x=0; x<tcw.cols; x++) {
            float element= tcw.at<float>(x, y);
            // do someting with field "element" ...
        }
    }
} else {
    std::cout << "Warning: Empty/blurry frame." << std::endl;
}
```

Didn't had the time to analyse accuracy and the interpreting the single elements yet.

Which elements represent position data? The first row?
Which elements represent the rotation data? The second row?
