### ISSUE TITLE
How does find the image corresponding to the key frame?

### ISSUE THREAD

**Issue by q412611827** [raulmur/ORB_SLAM2#691]
I have saved the map and point cloud. 
But I want to get the image corresponding to the key frame.
I need RGB information for the image to point cloud's RGB.

**Comment by justice-suri** [comment]
You can check the RGBD value of keyframe.

https://github.com/raulmur/ORB_SLAM2/blob/master/src/Tracking.cc#L207

**Comment by q412611827** [comment]
> You can check the RGBD value of keyframe.
> 
> https://github.com/raulmur/ORB_SLAM2/blob/master/src/Tracking.cc#L207

Thanks, I created a new MAT matrix storage image directly in the Frame class.
