### ISSUE TITLE
What is the matrix Tcr in Tracking.cpp

### ISSUE THREAD

**Issue by PierBJX** [raulmur/ORB_SLAM2#697]
Hi,

I was going through the Tracking.cpp file and I am not sure about what is going [here](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Tracking.cc#L488) _(line 488)_
```
   // Store frame pose information to retrieve the complete camera trajectory afterwards.
    if (!mCurrentFrame.mTcw.empty())
    {
        cv::Mat Tcr = mCurrentFrame.mTcw * mCurrentFrame.mpReferenceKF->GetPoseInverse();
        mlRelativeFramePoses.push_back(Tcr);
        mlpReferences.push_back(mpReferenceKF);
        mlFrameTimes.push_back(mCurrentFrame.mTimeStamp);
        mlbLost.push_back(mState == LOST);
    }
```

So far I understand that it is saving all the revelant information to save the camera trajectory. There are the current pose of the camera mCurrentFrame.mTcw (green rectangle in the viewer) and the current Key Frame reference (blue rectangle in the viewer) and the timestamp.
However, I don't really understand what is Tcr ? Why do we do the product of the current pose of the camera (Tcw) and the current **inverse** pose of the current key frame ?

**Comment by q412611827** [comment]
Tcr is the relative pose of the current frame and the reference frame.
System::SaveTrajectoryKITTI() will use it.

**Comment by PierBJX** [comment]
Thanks
