### ISSUE TITLE
Display current points on Map Viewer

### ISSUE THREAD

**Issue by PierBJX** [raulmur/ORB_SLAM2#705]
Using monocular, I would like to know if it was possible to color the current points that the camera sees (green square on "Current Frame" window) on the Map Viewer window.
 
![selection_006](https://user-images.githubusercontent.com/22519163/50830031-c4172380-1346-11e9-8d47-83b732450c36.png)

ORB SLAM uses two functions to get the points on the map ([code](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/MapDrawer.cc#L46)):
```
    const vector<MapPoint *> &vpMPs = mpMap->GetAllMapPoints();          // Black points
    const vector<MapPoint *> &vpRefMPs = mpMap->GetReferenceMapPoints(); // Red points
```

From these two vectors how could I find the current points displayed on the "Current Frame" window ?
I found that the current points displayed on the current frame window are mCurrentFrame.mvKeys. However, these points are not vector Map Point but a vector of KeyPoints.

**Comment by AlejandroSilvestri** [comment]
@PierBJX 

Let say you want to populate the custom variable

     const vector<MapPoint *> &vpCurrentMPs  = SomehowGetCurrentMapPoints();          // Green points

You can retrieve those mappoints from

    (vector<MapPoint*>) mCurrentFrame.mvpMapPoints  

This vector has size `mCurrentFrame.N` and most of its elements are null.

**Comment by PierBJX** [comment]
Thanks, I succeeded to do it. Here is the code to modify : 

**Map.h**

- Insert [line 54](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/include/Map.h#L54)
```
  // Function to manage the current points to color them in green
  void AddCurrentMapPoint(MapPoint *pMP);        // add
  void EraseCurrentMapPoint();                   // delete
  std::vector<MapPoint *> GetCurrentMapPoints(); // get
```
- Insert [line 72](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/include/Map.h#L72)
`   std::set<MapPoint *> mspCurrentMapPoints; // Current map points`

**MapDrawer.h**
- Change [line 41](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/include/MapDrawer.h#L41) with
`   void DrawMapPoints(const bool bDrawCurrentPoints);`

**Map.cc**
- Insert [line 132](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Map.cc#L132)
```
void Map::AddCurrentMapPoint(MapPoint *pMP)
{
    unique_lock<mutex> lock(mMutexMap);
    mspCurrentMapPoints.insert(pMP);
}

void Map::EraseCurrentMapPoint()
{
    unique_lock<mutex> lock(mMutexMap);
    mspCurrentMapPoints.clear();
}

vector<MapPoint *> Map::GetCurrentMapPoints()
{
    unique_lock<mutex> lock(mMutexMap);
    return vector<MapPoint *>(mspCurrentMapPoints.begin(), mspCurrentMapPoints.end());
}
```

- Add in the [clear function line 118](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Map.cc#L118)
 ` mspCurrentMapPoints.clear();`


**MapDrawer.cc**
- Change [line 44](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/MapDrawer.cc#L44) with
`void MapDrawer::DrawMapPoints(const bool bDrawCurrentPoints)`

- Insert after the [line 80](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/MapDrawer.cc#L80)
```
    if (bDrawCurrentPoints)
    {
        // Define points
        glPointSize(5);
        glBegin(GL_POINTS);
        glColor3f(0.0, 1.0, 0.0);

        // All map points
        for (std::vector<MapPoint *>::const_iterator i = vpCurrentMPs.begin(); i != vpCurrentMPs.end(); i++)
        {
            if ((*i)->isBad())
                continue;
            cv::Mat pos = (*i)->GetWorldPos();
            glVertex3f(pos.at<float>(0), pos.at<float>(1), pos.at<float>(2));
        }
        glEnd();
    }
```

**Tracking.cc**
- Insert [line 419](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Tracking.cc#L419)
```
        // Empty the current map points vector
        mpMap->EraseCurrentMapPoint();

        // Add the current map points in the vector
        for (int i = 0; i < mCurrentFrame.N; i++)
        {
            if (mCurrentFrame.mvpMapPoints[i] && !mCurrentFrame.mvbOutlier[i])
            {
                mpMap->AddCurrentMapPoint(mCurrentFrame.mvpMapPoints[i]);
            }
        }

```

**Viewer.cc**
- Change [line 68](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Viewer.cc#L68) with
`    pangolin::CreatePanel("menu").SetBounds(0.0, 1.0, 0.0, pangolin::Attach::Pix(185));`

- Insert [line 72](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Viewer.cc#L72)
`    pangolin::Var<bool> menuShowCurrentPoints("menu.Show Current Points", true, true);`

- Change [line 133](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Viewer.cc#L133) with
`            mpMapDrawer->DrawMapPoints(menuShowCurrentPoints);`

**Comment by AlejandroSilvestri** [comment]
@PierBJX , glad to know you succeeded.

If you have any time, please post a screen capture, and better if you can upload a video to YouTube and share the link here with us.

**Comment by PierBJX** [comment]
@AlejandroSilvestri, I have no time yet to do the video but I will and share the link.
For the moment, here is the screenshot
![image](https://user-images.githubusercontent.com/22519163/51477268-3e549880-1d88-11e9-841f-07e947929987.png)
As you can see the current points are in green.

**Comment by rahulsharma11** [comment]
Hi @PierBJX ,
I tried exact same modifications but still getting only red and black points.
Is there any other modification left?
Thanks.

**Comment by PierBJX** [comment]
@rahulsharma11 
Have you built orb-slam ?
Because it's supposed to work. Send a screenshot of the viewer GUI

**Comment by rahulsharma11** [comment]
Yes, i have built orbslam.

![orbslam2](https://user-images.githubusercontent.com/28132746/52471559-2fa71780-2bb7-11e9-9c14-cba312ddbca5.png)

**Comment by KaninchenM** [comment]
> Thanks, I succeeded to do it. Here is the code to modify :
> 
> **Map.h**
> 
> * Insert [line 54](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/include/Map.h#L54)
> 
> ```
>   // Function to manage the current points to color them in green
>   void AddCurrentMapPoint(MapPoint *pMP);        // add
>   void EraseCurrentMapPoint();                   // delete
>   std::vector<MapPoint *> GetCurrentMapPoints(); // get
> ```
> 
> * Insert [line 72](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/include/Map.h#L72)
>   `   std::set<MapPoint *> mspCurrentMapPoints; // Current map points`
> 
> **MapDrawer.h**
> 
> * Change [line 41](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/include/MapDrawer.h#L41) with
>   `   void DrawMapPoints(const bool bDrawCurrentPoints);`
> 
> **Map.cc**
> 
> * Insert [line 132](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Map.cc#L132)
> 
> ```
> void Map::AddCurrentMapPoint(MapPoint *pMP)
> {
>     unique_lock<mutex> lock(mMutexMap);
>     mspCurrentMapPoints.insert(pMP);
> }
> 
> void Map::EraseCurrentMapPoint()
> {
>     unique_lock<mutex> lock(mMutexMap);
>     mspCurrentMapPoints.clear();
> }
> 
> vector<MapPoint *> Map::GetCurrentMapPoints()
> {
>     unique_lock<mutex> lock(mMutexMap);
>     return vector<MapPoint *>(mspCurrentMapPoints.begin(), mspCurrentMapPoints.end());
> }
> ```
> 
> * Add in the [clear function line 118](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Map.cc#L118)
>   ` mspCurrentMapPoints.clear();`
> 
> **MapDrawer.cc**
> 
> * Change [line 44](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/MapDrawer.cc#L44) with
>   `void MapDrawer::DrawMapPoints(const bool bDrawCurrentPoints)`
> * Insert after the [line 80](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/MapDrawer.cc#L80)
> 
> ```
>     if (bDrawCurrentPoints)
>     {
>         // Define points
>         glPointSize(5);
>         glBegin(GL_POINTS);
>         glColor3f(0.0, 1.0, 0.0);
> 
>         // All map points
>         for (std::vector<MapPoint *>::const_iterator i = vpCurrentMPs.begin(); i != vpCurrentMPs.end(); i++)
>         {
>             if ((*i)->isBad())
>                 continue;
>             cv::Mat pos = (*i)->GetWorldPos();
>             glVertex3f(pos.at<float>(0), pos.at<float>(1), pos.at<float>(2));
>         }
>         glEnd();
>     }
> ```
> 
> **Tracking.cc**
> 
> * Insert [line 419](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Tracking.cc#L419)
> 
> ```
>         // Empty the current map points vector
>         mpMap->EraseCurrentMapPoint();
> 
>         // Add the current map points in the vector
>         for (int i = 0; i < mCurrentFrame.N; i++)
>         {
>             if (mCurrentFrame.mvpMapPoints[i] && !mCurrentFrame.mvbOutlier[i])
>             {
>                 mpMap->AddCurrentMapPoint(mCurrentFrame.mvpMapPoints[i]);
>             }
>         }
> ```
> 
> **Viewer.cc**
> 
> * Change [line 68](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Viewer.cc#L68) with
>   `    pangolin::CreatePanel("menu").SetBounds(0.0, 1.0, 0.0, pangolin::Attach::Pix(185));`
> * Insert [line 72](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Viewer.cc#L72)
>   `    pangolin::Var<bool> menuShowCurrentPoints("menu.Show Current Points", true, true);`
> * Change [line 133](https://github.com/raulmur/ORB_SLAM2/blob/f2e6f51cdc8d067655d90a78c06261378e07e8f3/src/Viewer.cc#L133) with
>   `            mpMapDrawer->DrawMapPoints(menuShowCurrentPoints);`

Thanks to PierBJX.
Remember to add the following content to function`DrawMapPoints(const bool bDrawCurrentPoints)` in file `MapDrawer.cc`:
    `const vector<MapPoint*> &vpCurrentMPs = mpMap->GetCurrentMapPoints(); `
After `const vector<MapPoint*> &vpRefMPs = mpMap->GetReferenceMapPoints();`
Or you will not compile well.

**Comment by RehabHsn** [comment]
If I want to save the map points to PCL format or any format, how can I do that?
Thanks in advance

**Comment by KaninchenM** [comment]
您的邮件已收到，我会尽快回复您！

**Comment by AlejandroSilvestri** [comment]
@RehabHsn 

This project let you save and load your maps:

https://github.com/AlejandroSilvestri/osmap

MapPoints go in separated files.  You can program it to save in other formats.
