### ISSUE TITLE
error libc++abi.dylib on Mac 

### ISSUE THREAD

**Issue by coskunyerli** [raulmur/ORB_SLAM2#74]
I execute mono_kitti but I get an error like this

2016-04-22 10:04:43.803 mono_kitti[83533:2259854] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff92e5a03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8fa5576e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff92e59e1a +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fff923bf99b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Foundation                          0x00007fff9234164f +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 156
	5   AppKit                              0x00007fff9a1f6c41 -[NSApplication run] + 928
	6   QtGui                               0x00000001072f4f0d _ZN26QEventDispatcherMacPrivate22ensureNSAppInitializedEv + 125
	7   QtGui                               0x00000001072f47ab _ZN19QEventDispatcherMac13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 693
	8   QtCore                              0x0000000107f6e787 _ZN16QCoreApplication13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 81
	9   libopencv_highgui.2.4.dylib         0x0000000105d458af cvWaitKey + 193
	10  libORB_SLAM2.dylib                  0x00000001054c1222 _ZN9ORB_SLAM26Viewer3RunEv + 1810
	11  libORB_SLAM2.dylib                  0x00000001054af511 _ZNSt3__114__thread_proxyINS_5tupleIJMN9ORB_SLAM26ViewerEFvvEPS3_EEEEEPvS8_ + 113
	12  libsystem_pthread.dylib             0x00007fff9181505a _pthread_body + 131
	13  libsystem_pthread.dylib             0x00007fff91814fd7 _pthread_body + 0
	14  libsystem_pthread.dylib             0x00007fff918123ed thread_start + 13
)

"libc++abi.dylib: terminating with uncaught exception of type NSException"

**Comment by IamMegatron2025** [comment]
@coskunyerli  meet the same error. how do you solve it?
