### ISSUE TITLE
Failed to load Image

### ISSUE THREAD

**Issue by deepakyeleshetty** [raulmur/ORB_SLAM2#774]
NOTE: Issue is the same as https://github.com/raulmur/ORB_SLAM2/issues/768, but it was closed without a solution. Was wondering if there is any solution.

OS: Ubuntu 16.04 LTS VM on Windows.
OpenCV: 3.4.3
All dependencies installed successfully and compiling successfully.

I tried to run ORB_SLAM2 stereo example for the EuRoC dataset V2_01. I saved the data in a directory called "dataset" in the ORB_SLAM2 project root directory. The terminal throws an error "Failed to load image at \path_to_the_first_image_in_the_sequence\" as shown below.

`PROCESSING EROC SAMPLE - SEQUENCE V2_01

ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Stereo

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Camera Parameters: 
- fx: 435.205
- fy: 435.205
- cx: 367.452
- cy: 252.201
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 20
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1200
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Depth Threshold (Close/Far Points): 3.85272

-------
Start processing sequence ...
Images in the sequence: 2280

Failed to load image at: /dataset/mav0/cam0/data//1413393212255760384.png
`

The message is similar to the one in the issue referenced above. Could anyone please let me know why this happens and what the solution could be?

Thanks!

**Comment by gsenkowski** [comment]
Hello,

maybe there is an additional '/' somwhere in the path to the images wich leads to the double '/' after 'data' before '1413393212255760384.png' in
/dataset/mav0/cam0/data//1413393212255760384.png
 the needed '/' between the folder and the file is automatically added, so the path to the images shouldn't have a trailing '/'

**Comment by deepakyeleshetty** [comment]
Hello @gsenkowski ,

Thanks a lot for pointing it out! I completely overlooked it. There was also another '/' in the beginning which was also a mistake. I corrected it and it now works. I am closing the issue. Thanks again!
