### ISSUE TITLE
Monocular TUM example runs single thread on a single CPU

### ISSUE THREAD

**Issue by apatzer** [raulmur/ORB_SLAM2#79]
Just got ORB-SLAM2 up and running on a Mac. When I run the Monocular TUM on the Frieburg1 dataset, it runs for hours (still going).

```
./Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUM1.yaml ~/Downloads/rgbd_dataset_freiburg1_xyz/rgb
```

Activity Monitor shows a single CPU (I have 8 cores...7 of them not being used) and a single thread. Where's the real-time performance? Have I compiled things incorrectly? I'm on a 16GB machine with a solid processor, but no CUDA (Mac's use an Intel GPU).

![image](https://cloud.githubusercontent.com/assets/2538644/14804489/0ef1f220-0bb8-11e6-93ff-994774c0c30a.png)

**Comment by TheKiffer** [comment]
Change the command for it to point at the sequence folder and not the image sequence within:

`./Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUM1.yaml ~/Downloads/rgbd_dataset_freiburg1_xyz/`

**Comment by apatzer** [comment]
Yep, that works. Otherwise it's caught in an infinite loop.
