### ISSUE TITLE
TUM2 freiburg2 pioneer example failure

### ISSUE THREAD

**Issue by hoonkai** [raulmur/ORB_SLAM2#804]
I've been trying to repeatedly run the TUM2 freiburg2 pioneer example using `./Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUM2.yaml $TUM_PATH`, but the output I get is always incomplete and SLAM loses track after a few seconds. Here are some resulting points:

![Screen Shot 2019-08-25 at 9 17 19 pm](https://user-images.githubusercontent.com/14197204/63649220-5a854180-c77e-11e9-9470-cd9d234121a4.png)

This is the [video](https://youtu.be/bkd3aLPLlTk) of the entire process. As you can see, the keyframes are disconnected and the first keyframe was generated quite late into the sequence ([0:46](https://youtu.be/bkd3aLPLlTk?t=46)). Tracking only lasted for 7 seconds before it stopped identifying ORBs/points. Keyframes were again generated at around [1:57](https://youtu.be/bkd3aLPLlTk?t=117).

Does anyone know why tracking is flaky? Is this normal and expected behaviour?

**Comment by ihmc3jn09hk** [comment]
> I've been trying to repeatedly run the TUM2 freiburg2 pioneer example using `./Examples/Monocular/mono_tum Vocabulary/ORBvoc.txt Examples/Monocular/TUM2.yaml $TUM_PATH`, but the output I get is always incomplete and SLAM loses track after a few seconds. Here are some resulting points:
> 
> ![Screen Shot 2019-08-25 at 9 17 19 pm](https://user-images.githubusercontent.com/14197204/63649220-5a854180-c77e-11e9-9470-cd9d234121a4.png)
> 
> This is the [video](https://youtu.be/bkd3aLPLlTk) of the entire process. As you can see, the keyframes are disconnected and the first keyframe was generated quite late into the sequence ([0:46](https://youtu.be/bkd3aLPLlTk?t=46)). Tracking only lasted for 7 seconds before it stopped identifying ORBs/points. Keyframes were again generated at around [1:57](https://youtu.be/bkd3aLPLlTk?t=117).
> 
> Does anyone know why tracking is flaky? Is this normal and expected behaviour?

Same here. Sometimes it does not even found a valid initialization. Could you please share the solution?
