### ISSUE TITLE
The unit of distance in depth map?: Can not see the key points in map when using my own RGB-D sequence

### ISSUE THREAD

**Issue by MRinel** [raulmur/ORB_SLAM2#839]
Hello everyone,
I use my own RGB-D squence to test ORB_SALM2 but cannot see the key points in display.
**First**,RGB-D images were from TUM RGB , predicted by network and output in meters. (I have no RGB-D camera )
Here is the depth matrix:
![20191114215734](https://user-images.githubusercontent.com/28338959/68863182-d2358d80-0729-11ea-9818-b4eebeb444b1.png)

**Second**, after normalization for saving, the shape of RGB-D was [224 ,224, 4]. 
![20191114215911](https://user-images.githubusercontent.com/28338959/68863295-090ba380-072a-11ea-8bc5-9e2d97ed4af2.png)

Then, using the RGB-D routine, but I couldn't see the key points. It seems that there is something wrong with the distance because the key points are jammed together... like:
![20191114221753](https://user-images.githubusercontent.com/28338959/68865212-65bc8d80-072d-11ea-8881-112679503c44.png)

In author's example ,the shape of TUM RGB-D is [640,480], I wonder that what is the unit of  distance in RGB-D,meter or millimeter feed in SLAM system? and ,any device for my problem? Thanks a lot !!
Best wishes.

**Comment by collinabidi** [comment]
I'm having the same issue, but I'm using the Intel RealSense D435 sensor to make my own RGB-D sequences.

What I've found is that I get a better result by playing with the DepthMapFactor and ThDepth values in the TUM_*.yaml file provided. With that said, I still am having problems with inaccurate tracking and keypoints extremely close together.

![tracking](https://user-images.githubusercontent.com/29078081/68964258-e7043680-07a6-11ea-893a-6481b5631041.png)

In this result, I was able to get a somewhat accurate representation by adjusting those values. However, the path it takes isn't true to what it should be.

**Comment by MRinel** [comment]
@collinabidi , Is it getting too many feature points? Or you can scroll in or out to see it.
For me, after adjusting the factors,**"DepthMapFactor"**and **"ThDepth"** , results are slightly better...like:
![20191118122105_看图王](https://user-images.githubusercontent.com/28338959/69024528-0fd23900-09fe-11ea-9207-025020a4a16f.png)
There is still much work to be done for using my own video.
By the way, I am not clear with **"DepthMapFactor"**...and this part in **Tracking.cc**:
`if(sensor==System::RGBD)
{ 
    mDepthMapFactor = fSettings["DepthMapFactor"];
    if(fabs(mDepthMapFactor)<1e-5)
        mDepthMapFactor=1;
    else
        mDepthMapFactor = 1.0f/mDepthMapFactor;
    }`

`if((fabs(mDepthMapFactor-1.0f)>1e-5) || imDepth.type()!=CV_32F)
        imDepth.convertTo(imDepth,CV_32F,mDepthMapFactor);`

I would appreciate it if anyone could explain it, Thanks a lot! 
 
Best Wishes :)

**Comment by collinabidi** [comment]
@MRinel For this particular map it does get way too many feature points. I am taking a video of a highly cluttered environment though, so zooming out doesn't really help much anyways (in my case).

I'm not exactly clear what that means either. I know that when I record my video, I can set my depth magnitude value to whatever value I want, but it seems like trial and error was the only thing that helped me find better values.

**Comment by MRinel** [comment]
@collinabidi ,My guess is that "DepthMapFactor" may represent the scaling factor between true scale and displaying in the map, because the origin value in authors' is 5000.0 ,(maybe the unit of true distance is millimeter,mine is in meters), and when I set it to 4, these feature points can be found very well. So, "DepthMapFactor" is just a factor to display a map better. We need to keep trying to find a more proper value.

**Comment by collinabidi** [comment]
@MRinel I found that 4 seemed to work for me as well, not sure why that was good.

**Comment by Mechazo11** [comment]
@collinabidi Hi I know this is a old post, but are you familiar with a technique of finding the DepthMapFactor itself for a camera not previously used in ORB-SLAM3? For instance, I am trying to use the ORBEC ASTRA S camera and so far I haven't found an exact method of determining this value
