### ISSUE TITLE
Makefile:83: recipe for target 'all' failed

### ISSUE THREAD

**Issue by dhrupad-u** [raulmur/ORB_SLAM2#863]
I am getting this error even after installing all the dependencies and running `build.sh`.
I have installed OpenCV 4.2.0, Eigen 3.3 and running the code on Ubuntu OS.

`CMakeFiles/ORB_SLAM2.dir/build.make:446: recipe for target 'CMakeFiles/ORB_SLAM2.dir/src/Sim3Solver.cc.o' failed
make[2]: *** [CMakeFiles/ORB_SLAM2.dir/src/Sim3Solver.cc.o] Error 1
compilation terminated.
CMakeFiles/ORB_SLAM2.dir/build.make:470: recipe for target 'CMakeFiles/ORB_SLAM2.dir/src/Initializer.cc.o' failed
make[2]: *** [CMakeFiles/ORB_SLAM2.dir/src/Initializer.cc.o] Error 1
CMakeFiles/Makefile2:252: recipe for target 'CMakeFiles/ORB_SLAM2.dir/all' failed
make[1]: *** [CMakeFiles/ORB_SLAM2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by r0mac09** [comment]
cmake is not looking for OpencCV 4, you'll need to add `find_package(OpenCV 4 QUIET)` in CMakeLists.txt, if you insert it around other find_package you should be fine
