### ISSUE TITLE
How to adjust camera settings for images recorded from AirSimm

### ISSUE THREAD

**Issue by cslavenc** [raulmur/ORB_SLAM2#867]
Hey everyone! I have a bagfile with images from two cameras for stereo vision. When I launch orb_slam2_ros and play the bagfile in another terminal, it always loses tracking:
New map created with 176 points
Track lost soon after initialisation, reseting...
System Reseting
Reseting Local Mapper... done
Reseting Loop Closing... done
Reseting Database... done
New map created with 105 points
Track lost soon after initialisation, reseting...
System Reseting
Reseting Local Mapper... done
Reseting Loop Closing... done
Reseting Database... done
and so on.

Also, the view mode looks strange. The upper third is kind of squeezed and the rest below looks quite distorted.
Any hints? Let me know if you need more information. Would be great to use data from AirSim and get odometry estimates in the end.

![error_os2](https://user-images.githubusercontent.com/52094605/75098351-5dd67a00-55b5-11ea-9afa-64f12d6a1fde.PNG)

**Comment by catproof** [comment]
how are you creating this rosbag file?
