### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by pntbranch** [raulmur/ORB_SLAM2#87]
I am getting Segmentation fault (Core dumped) when I run both the Mono Kitti and Tum examples. They display for a few seconds and then crash. Any idea on how to fix this?

So the images display and it says "Trying to Initialize". Looking at the other window, the image of the camera does not move at all. The program then crashes as soon as the first set of slam points are plotted.

**Comment by Ellon** [comment]
@pntbranch Did you solve your problem? If yes, how did you do?
