### ISSUE TITLE
Creating my own vocabulary

### ISSUE THREAD

**Issue by alejodosr** [raulmur/ORB_SLAM2#9]
Hi, 

I am trying to re-create my own vocabulary file, in order to adapt the ORB-SLAM2 algorithm to the camera streaming in a Gazebo simulation. I use DBow2 to create both the vocabulary file _*_voc.yml.tgz_ and the _*_db.yml.tgz_. 

However, the ORB-SLAM2 algorithm requires a _*.txt_ vocabulary file (that is suppose to be ¿serialized?).

¿How can I generate the _*.txt_ from the files I have mentioned?

Thanks

**Comment by raulmur** [comment]
Use saveToTextFile function in TemplatedVocabulary.h (the one I provide, not the original one).

**Comment by alejodosr** [comment]
Thanks, I'll try that funciton. To properly generate the vocabulary, is it needed to use ORB-features? (or SURF can be used..) Sorry if it is a silly question, I am a beginner in this field.

**Comment by raulmur** [comment]
You have to use ORB features as long as you continue using them in ORB-SLAM.

**Comment by agharsh11** [comment]
@raulmur i am trying to implement ORB SLAM for underwater images should i make a new vocabulary or the one provided is sufficient....
thanks

**Comment by manthan99** [comment]
Have a look at this repo for step by step procedure to create your own vocabulary:
https://github.com/manthan99/ORB_SLAM_vocab-build
