### ISSUE TITLE
white display problem in ORB_SLAM2 on mac

### ISSUE THREAD

**Issue by coskunyerli** [raulmur/ORB_SLAM2#91]
I try to build ORB_SLAM2 and succesfully built.

but I get some problem. when I run ORB_SLAM program Pangolin views are white. there is no image on the screen just white, However program is running.

Any idea for solving problem ?

**Comment by TimingSpace** [comment]
I meet the same problem, have you solve it?

**Comment by zzzzzq** [comment]
Hello! I met similar problem as yours', do you have any solution?

**Comment by coskunyerli** [comment]
I don't find any solution on mac, To find the problem, I installed linux parallel
