### ISSUE TITLE
Nothing shows up while run ros command.

### ISSUE THREAD

**Issue by lbq779660843** [raulmur/ORB_SLAM2#947]
I post these results after running corresponding commands.

`roscore`
![2020-10-12 15-17-47屏幕截图](https://user-images.githubusercontent.com/27773249/95716814-9ccd5300-0c9e-11eb-997f-3090f1304e11.png)

`roslaunch realsense2_camera rs_rgbd.launch`
![2020-10-12 15-22-40屏幕截图](https://user-images.githubusercontent.com/27773249/95717039-f03fa100-0c9e-11eb-912c-974b56dddbb2.png)
![2020-10-12 15-23-06屏幕截图](https://user-images.githubusercontent.com/27773249/95717040-f2a1fb00-0c9e-11eb-80ee-0f2fe92c9451.png)
![2020-10-12 15-23-31屏幕截图](https://user-images.githubusercontent.com/27773249/95717045-f46bbe80-0c9e-11eb-959e-42271c235490.png)

`rosrun ORB_SLAM2 RGBD Vocabulary/ORBvoc.txt Examples/RGB-D/TUM1.yaml`
![2020-10-12 15-25-07屏幕截图](https://user-images.githubusercontent.com/27773249/95717154-211fd600-0c9f-11eb-9e54-b2fc9c45587f.png)

Can anyone help me to fix this?

**Comment by Tabbleman** [comment]
how did u fixed it
