### ISSUE TITLE
Change displaysize of the Current Frame window?

### ISSUE THREAD

**Issue by DaturoDewitt** [raulmur/ORB_SLAM2#950]
Hey I'm having trouble with viewing the current frame in my Linux VM.

My phone records videos/pictures in Full HD 1080px and the Viewer will always clip out of my screen. Is there an easy way to change the size of the window?

**Comment by martinakos** [comment]
@JensAltst I'm looking for the same feature. Have you found a way of reducing the size of the current frame?

**Comment by martinakos** [comment]
I found an easy way of resizing the current frame window. 
search for: 
`cv::namedWindow("ORB-SLAM2: Current Frame")`
in Viewer.cc
and replace with:
`cv::namedWindow("ORB-SLAM2: Current Frame", cv::WINDOW_NORMAL);`
then rebuild and the window will be resizable.

**Comment by DaturoDewitt** [comment]
Thanks that helped a lot!
