### ISSUE TITLE
Cmake error (error: static assertion failed) for Ubuntu 20.0.4 running Eigen 3.2.10

### ISSUE THREAD

**Issue by sihengt** [raulmur/ORB_SLAM2#958]
Ran into an error during build where:

/path/to/orb-slam/ORB_SLAM2/src/LoopClosing.cc:438:21:   required from here
/usr/include/c++/9/bits/stl_map.h:122:71: error: static assertion failed: std::map must have the same value_type as its allocator
  122 |       static_assert(is_same<typename _Alloc::value_type, value_type>::value,
      |                                                                       ^~~~~
make[2]: *** [CMakeFiles/ORB_SLAM2.dir/build.make:102: CMakeFiles/ORB_SLAM2.dir/src/LoopClosing.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:250: CMakeFiles/ORB_SLAM2.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by sihengt** [comment]
Within this blog entry by 嵙杰 (https://blog.csdn.net/lixujie666/article/details/90023059), a suggestion for a quick fix amending LoopClosing.h is shown as follows:

In /path/to/orb-slam/ORB_SLAM2/include/LoopClosing.h line 50:

Change:
`typedef map<KeyFrame*,g2o::Sim3,std::less<KeyFrame*>,
        Eigen::aligned_allocator<std::pair<const KeyFrame*, g2o::Sim3> > > KeyFrameAndPose;`

to:
`typedef map<KeyFrame*,g2o::Sim3,std::less<KeyFrame*>,
        Eigen::aligned_allocator<std::pair<KeyFrame const*, g2o::Sim3> > > KeyFrameAndPose;`

This will prevent the std::map error and allow the build to pass successfully.

**Comment by Tabbleman** [comment]
i changed this in LoopClosing.h:line 49
`typedef map<KeyFrame*,g2o::Sim3,std::less<KeyFrame*>, Eigen::aligned_allocator<std::pair<KeyFrame * const, g2o::Sim3> > > KeyFrameAndPose;` and fixed this.
