### ISSUE TITLE
mapping problem in simulation

### ISSUE THREAD

**Issue by mmahdavian** [raulmur/ORB_SLAM2#965]
Hi. I am trying to make orb-slam map in habitat simulation with replica dataset. So far I have generated path and got images and made rosbag from them. ORB-SLAM tries to make a map from the published images. The path is a C shaped motion. for first parts of it the map is really good, but after rotations the mapping doesn't work properly. Does anyone know how can I fix it? I have attached my map and habitat.yaml file and a ground truth showing the correct path.
[habitat.yaml.zip](https://github.com/raulmur/ORB_SLAM2/files/5706963/habitat.yaml.zip)

![Screenshot from 2020-12-16 19-46-00](https://user-images.githubusercontent.com/65621717/102442893-4fd96600-3fda-11eb-9605-a6deb9efb95b.png)

![Figure_1](https://user-images.githubusercontent.com/65621717/102442975-831bf500-3fda-11eb-9910-c231f004e872.png)

**Comment by mmahdavian** [comment]
I increased the image size to 720x720 and modified habitat.yaml file based on it and the problem is solved

**Comment by jediofgever** [comment]
what was the image size before  720x720 ? , I am even using 1280x720 but still same issue
