### ISSUE TITLE
where is the GetKeyFrames function in System.h

### ISSUE THREAD

**Issue by linpeisensh** [raulmur/ORB_SLAM2#966]
@raulmur 
Thank you for your work!
I have no problem with build this C++ ORB_SLAM2, but when I build ORB_SLAM2 python_binding, error occurs because there is no GetKeyFrames in include/System.h.
Could you please give me this function and help me out?

**Comment by oorrppp2** [comment]
I have the same problem as you.
How did you solve it?
Thank you :)

**Comment by linpeisensh** [comment]
https://github.com/jskinn/ORB_SLAM2-PythonBindings/blob/master/orbslam-changes.diff
Follow this.

**Comment by oorrppp2** [comment]
Thank u!
It works for me :)
