### ISSUE TITLE
Using ORB-SLAM2 with stereo camera in gazebo

### ISSUE THREAD

**Issue by kazuma-takeuchi-jpn** [raulmur/ORB_SLAM2#968]
Hi!
I'm trying to run ORB-SLAM2 with stereo camera in gazebo. I use ros melodic to do these things. Stereo camera works well, and ros topic about left and right camera is in the rostopic list. However, when I try to run ORB-SLAM2, it subscribe only left camea topic, in other words, only the image on the left side of the camera will be displayed. 

![Screenshot from 2020-12-23 17-13-16](https://user-images.githubusercontent.com/76512537/102974667-456f1d00-4542-11eb-913f-c8703f4429ac.png)

This is the simulation environment.

![Screenshot from 2020-12-23 17-13-01](https://user-images.githubusercontent.com/76512537/102974708-53bd3900-4542-11eb-82c1-bb4e92ed5e36.png)

This is the screen shot when I tried to run ORB-SLAM2

![Screenshot from 2020-12-23 17-11-25](https://user-images.githubusercontent.com/76512537/102974738-620b5500-4542-11eb-9207-fc9cf0c26500.png)

This is the terminal screen.

Does anyone know how to solve this problems?  I thank you in advance, and Merry Christmas!

**Comment by Spnd77** [comment]
Hi,
Can you tell me how we can Connect Gazebo and ORBSLAM?
Do you know any reference code for it?
@kazuma-takeuchi-jpn @raulmur 
Thanks
